# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 12:09
from __future__ import unicode_literals

import Sender.validators
from django.db import migrations, models
import multi_email_field.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0002_masssender_bcc_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masssender',
            options={
                'verbose_name': '\u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0443',
                'verbose_name_plural': '\u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438'},
        ),
        migrations.AlterField(
            model_name='masssender',
            name='bcc_list',
            field=multi_email_field.fields.MultiEmailField(
                blank=True,
                help_text='\u0414\u043e\u0431\u0430\u0432\u044c\u0442\u0435 \u0441\u043f\u0438\u0441\u043e\u043a \u0434\u043b\u044f \u0440\u0430\u0441\u0441\u043b\u044b\u043a\u0438 \u043f\u043e \u043e\u0434\u043d\u043e\u043c\u0443 \u0430\u0434\u0440\u0435\u0441\u0443 \u0432 \u0441\u0442\u0440\u043e\u043a\u0435',
                null=True,
                verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a \u0434\u043b\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='masssender',
            name='mail_attachment',
            field=models.FileField(
                upload_to=b'',
                validators=[
                    Sender.validators.validate_file_extension],
                verbose_name='\u0412\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='masssender',
            name='mailbody',
            field=tinymce.models.HTMLField(
                verbose_name='\u0422\u0435\u043b\u043e \u043f\u0438\u0441\u044c\u043c\u0430'),
        ),
        migrations.AlterField(
            model_name='masssender',
            name='sender_name',
            field=models.EmailField(
                max_length=30,
                verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c \u043e\u0442'),
        ),
    ]
