# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 13:50
from __future__ import unicode_literals

import Sender.storages
import Sender.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0003_auto_20151204_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masssender',
            options={
                'verbose_name': '\u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0430',
                'verbose_name_plural': '\u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438'},
        ),
        migrations.AlterField(
            model_name='masssender',
            name='mail_attachment',
            field=models.FileField(
                storage=Sender.storages.OverwriteStorage(),
                upload_to=b'',
                validators=[
                    Sender.validators.validate_file_extension],
                verbose_name='\u0412\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
