# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0009_auto_20151207_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masssender',
            name='pub_date',
            field=models.DateTimeField(
                default=datetime.datetime(
                    2015,
                    12,
                    7,
                    11,
                    55,
                    5,
                    877912),
                editable=False,
                verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438'),
        ),
    ]
