# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 09:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0010_auto_20151207_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='masssender',
            name='mail_theme',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='\u0422\u0435\u043c\u0430 \u043f\u0438\u0441\u044c\u043c\u0430'),
        ),
        migrations.AlterField(
            model_name='masssender',
            name='pub_date',
            field=models.DateTimeField(
                default=datetime.datetime(
                    2015,
                    12,
                    7,
                    12,
                    31,
                    14,
                    40535),
                editable=False,
                verbose_name='\u0414\u0430\u0442\u0430 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u044f \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438'),
        ),
    ]
