# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 09:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import multi_email_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0012_auto_20151207_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masssender',
            name='bcc_list',
            field=multi_email_field.fields.MultiEmailField(
                help_text='\u0414\u043e\u0431\u0430\u0432\u044c\u0442\u0435 \u0441\u043f\u0438\u0441\u043e\u043a \u0434\u043b\u044f \u0440\u0430\u0441\u0441\u043b\u044b\u043a\u0438 \u043f\u043e \u043e\u0434\u043d\u043e\u043c\u0443 \u0430\u0434\u0440\u0435\u0441\u0443 \u0432 \u0441\u0442\u0440\u043e\u043a\u0435',
                null=True,
                verbose_name='\u041a\u043e\u043c\u0443:'),
        ),
        migrations.AlterField(
            model_name='masssender',
            name='mail_theme',
            field=models.CharField(
                max_length=200,
                null=True,
                verbose_name='\u0422\u0435\u043c\u0430 \u043f\u0438\u0441\u044c\u043c\u0430'),
        ),
        migrations.AlterField(
            model_name='masssender',
            name='pub_date',
            field=models.DateTimeField(
                default=datetime.datetime(
                    2015,
                    12,
                    7,
                    12,
                    37,
                    39,
                    371657),
                editable=False,
                verbose_name='\u0414\u0430\u0442\u0430 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u044f \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438'),
        ),
    ]
